### ISSUE TITLE
The test_custom_load test fails if run on the full test suite

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-testcases#607]
See:
https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/558-1692384177/index.html#suites/204286fb93f613360849054c8f51bbd5/98cba8bf93f5fac7/

```
19:13:53 [WARNING] Can't connect to host 127.0.0.1, will retry. Error: [Errno 2] No such file or directory: '../neofs-dev-env/services/k6_node/id_ed25519'
19:13:53 [WARNING] Can't connect to host 127.0.0.1, will retry. Error: [Errno 2] No such file or directory: '../neofs-dev-env/services/k6_node/id_ed25519'
19:13:53 [ERROR] Can't connect to host 127.0.0.1
Traceback (most recent call last):
  File "/home/runner/work/neofs-node/neofs-node/neofs-testcases/venv.local-pytest/lib/python3.10/site-packages/neofs_testlib/shell/ssh_shell.py", line 266, in _create_connection
    pkey=_load_private_key(self.private_key_path, self.private_key_passphrase),
  File "/home/runner/work/neofs-node/neofs-node/neofs-testcases/venv.local-pytest/lib/python3.10/site-packages/neofs_testlib/shell/ssh_shell.py", line 80, in _load_private_key
    return key_type.from_private_key_file(file_path, password)
  File "/home/runner/work/neofs-node/neofs-node/neofs-testcases/venv.local-pytest/lib/python3.10/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/runner/work/neofs-node/neofs-node/neofs-testcases/venv.local-pytest/lib/python3.10/site-packages/paramiko/ed25519key.py", line 57, in __init__
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../neofs-dev-env/services/k6_node/id_ed25519'
```

![image](https://github.com/nspcc-dev/neofs-testcases/assets/126654550/5a75ca99-43bd-4bcf-ae08-5bbf5949df77)

**Comment by evgeniiz321** [comment]
was caused by outdated dev-env, fixed
